dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
script:
  - cd decide
  - cp travis_local_settings.py local_settings.py
  - coverage run --branch --source=. ./manage.py test --keepdb
deploy:
  provider: heroku
  app: egc-dan2
  strategy: git
  api_key: a26a7a4b-5874-4e92-95f2-d6cc94a9f3df
  on:
    branch: master